support alternate quality
afq984/void-battery pull request #16
Opened 2020-10-13 08:53 UTC by spadea96334

2020-10-13 09:16 UTC, afq984 commented
現在寶石一定會 __的 開頭嗎？

2020-10-13 09:22 UTC, spadea96334 commented
__是指底線？

2020-10-13 09:23 UTC, spadea96334 commented
現在寶石會有變種，像是"相異的 XXXX"之類的

2020-10-13 09:28 UTC, spadea96334 commented
> 現在寶石一定會 __的 開頭嗎？

一般的寶石沒有 "__的" 的前綴，變種的才有

2020-10-13 12:03 UTC, afq984 requested changes
如果他的 `的` 後面一定是空白，我想改成 comment 那樣
讓以後萬一有新的形容詞 quality(?) 的時候跳 `KeyError` 出來，不會變成 `Default` 都沒發現

2020-10-13 12:03 UTC, afq984 commented on web/pobgen.py
> +    qualityId = ALTERNATE_MAP.get(alternate, 'Default')
```suggestion
    match = re.match(r'(%s)(.+)' % alt_matcher, item['typeLine'])
    alternate, gemName = match.groups()
    nameSpec = nebuloch.names.translate(gemName).replace(' Support', '')
    qualityId = ALTERNATE_MAP[alternate]
```

2020-10-15 07:48 UTC, afq984 approved these changes

2020-10-15 07:48 UTC, merged